dist: xenial
services:
- docker
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: nSETcSoAgGGWm+IIWugAvkIR6GnqdZy+b70IwswZIb2xxY2gEBMFhX1JWhhL05HL3luiY5w94JRXnX3w4fNR9jLQFGOS+4bWqpK+QEllUHPJgL3kdN6dkSjhbEvhVMkGYZ3PG3VHJ1jAp6vYKkO4H4gKS8lQm3bhqyT57nMO5fh7DQ83G3YY+JH43VWH7wMUyiVclvmPEMSnKrLDBHxlXvtbNfWYJrQm+G+xHWM4/opkX+1r0RPxSEsiA4KOlERzYmCRtd/NUo6sCs3xt3ECho1yoe7HT2H3UsrDohpm9m1hLVMqs1nbAAwis9XJtnwsQG3fUe+m2VnzScUThaPRjAZWB3axha0V3dg1dcBvAmb0rchD7BnwYDcpZnvKBk/nrTlDnaDHkUPdYVEtDHAgXUEpmUpSDsd30Ov627fLmkRmVD69DGBIsOMX55VdzCcpUPRAWfCJ5YVXUexDLGq/RenZX0PNO1B+Vo2lY6yCegzMjkZuCkO8zdznMMaYqnxZLlOBpJan1j5DaUsgAi+U+dpJ68Nr2vvSR4ODpahw2+xcugp44sjue2izhqbp8clG21cegPA7hVQ6FEQMEmID7l1QdlYfhhzXh2qzU3HakgE1tb7Mrj6eOaiBCzKg/kIAeCZIFuShNNWMXbrx8NftgakxtjW19krT8waGzAKtYzU=
  - secure: G9CstC0ziBZNgnf8mxqzaMEeuXIFPHc164uKrGxpA/4X6NuD8YjRnqaXSUbldxTawN+nlkW2uPjZtaV16Zv/J0uSuBmOCVdZ31b3tyswoJe2FfU8tSeLtCNtGrF+qZ/Kaik1ojG+CRYyrmMrZNkk6E0n4o/PZKIPoAPcH9VRDcCW0hch/hYvI0roacX6xE643j4OyJW3IfpoW2rnJKk4UA1keLfQKQhmbCILjppybqVJdD23uMzKF4qIQxjGbxyB4Qg86RZV/4y3u1D/5NNvbcnUHzcHW9oL3p/nvAMQLJj3z3Avj3T/y+nuWvgIjGyWBYGj7yDqlvIcJq1QQB/3717AVKALzPpyKXpNWtYHGDHm9r43N59qqeIqPMXaY7nwUDy4D550f4QPW1Sz4yotFnHYvOvf1BnFXMX9GBhv6ZQ5QGtD0p1/XDu3cGHcV/G0+o87OKh0bQBFFNVmnv4oEyDvXYymncSb8vRETKIxQVtfyyY7yRtJDMVGduUuL1CiUPEgyX36uJ9U2+KA04f5fD7CqsceCGYJzE4MFTUA7suiSpZl/QPTtdZVU1tAwNdS77r3Kjz/Rn9VBoxcHBR6jbBHrs5qD9Jcg5XtShTtCGSaUbAOb9vj9zU0INvLqPJ7j3vbK9mdrkg0jm5nDiW5ZgTN/bRqpUvvb9meg14johs=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
